kind: Project
apiVersion: garden.io/v2
name: angry-agent

variables:
  pr-number: ${local.env.PR_NUMBER || "local"}
  pr-namespace: angry-agent-pr-${var.pr-number}
  kube-context: "${local.env.GARDEN_KUBECONTEXT || (local.env.CI == 'true' ? 'local' : 'kubernetes-admin@kubernetes')}"
  current-namespace: ${environment.defaultNamespace || "default"}

sources:
  - name: central-base
    repositoryUrl: https://github.com/PolecatWorks/home-k8s.git#main

providers:
  - name: kubernetes
    context: ${var.kube-context}
    namespace: ${environment.namespace}
    deploymentRegistry:
      hostname: ghcr.io
      namespace: polecatworks
    environments:
      - pr
      - pr-local
      - default

environments:
  - name: default
    defaultNamespace: default
  - name: pr-local
    defaultNamespace: angry-agent-pr-local
  - name: pr
    defaultNamespace: angry-agent-pr-${var.pr-number}

---
kind: Deploy
type: helm
name: agent-be
description: "Deploy the backend agent"
dependencies:
  - deploy.angry-agent-secrets
source:
  path: charts/agent-be
include:
  - charts/agent-be/**/*
spec:
  values:
    configs:
      webservice:
        url: http://0.0.0.0:8080/agent-be
      persistence:
        db:
          connection:
            url: postgresql://cnpg-db0-cluster-rw.dbs:5432/angry_agent
      main_aiclient:
        ollama_base_url: http://ollama.ollama:11434
      packager_aiclient:
        ollama_base_url: http://ollama.ollama:11434
    secretName: db0-angry-agent-user
    env:
      - name: APP_PERSISTENCE__DB__CONNECTION__USERNAME
        valueFrom:
          secretKeyRef:
            name: db0-angry-agent-user
            key: username
      - name: APP_PERSISTENCE__DB__CONNECTION__PASSWORD
        valueFrom:
          secretKeyRef:
            name: db0-angry-agent-user
            key: password

    image:
      repository: ${local.env.AGENT_BE_IMAGE || "ghcr.io/polecatworks/angry-agent-be"}
      tag: ${local.env.AGENT_BE_TAG || "latest"}

---
kind: Deploy
type: helm
name: agent-ui
description: "Deploy the UI microfrontend"
spec:
  chart:
    url: oci://ghcr.io/polecatworks/mfe-shell/helm/nginx-view
    version: "0.1.0-main-20260210211011-05bbdec"
  values:
    image:
      repository: ${local.env.AGENT_UI_IMAGE || "ghcr.io/polecatworks/angry-agent-ui"}
      tag: ${local.env.AGENT_UI_TAG || "latest"}
      pullPolicy: Always
    env:
      - name: SERVE_ROOT
        value: /mfe/angry-agent
    config:
      contents:
        config.json: |
          {
            "apiUrl": "/agent-be/api"
          }

---
kind: RenderTemplate
template: push-secret-config
name: angry-agent-secrets
inputs:
  sourceSecretName: db0-angry-agent-user
  sourceNamespace: dbs
  remoteNamespace: ${environment.namespace}
