---
image:
  repository: ghcr.io/polecatworks/angry-agent-be/dev
  pullPolicy: Always
configs:
  persistence:
    db:
      connection:
        url: postgresql://cnpg-db0-cluster-rw.dbs:5432/angry_agent

volumes:
  - name: configs
    configMap:
      name: '{{ template "agent-be.fullname" . }}'
  - name: secrets
    projected:
      sources:
        - secret:
            name: db0-angry-agent-user
            items:
              - key: username
                path: persistence/db/connection/username
              - key: password
                path: persistence/db/connection/password
              # - key: gcp_llm_key
              #   path: aiclient/google_api_key
              # - key: CLIENTID
              #   path: bot/azure_bot_client/CLIENTID
              # - key: CLIENTSECRET
              #   path: bot/azure_bot_client/CLIENTSECRET
              # - key: TENANTID
              #   path: bot/azure_bot_client/TENANTID
