import operator
from typing import Annotated, List, Literal
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage


class MFEContent(BaseModel):
    mfe: str = Field(description="The source MFE where the component is defined (e.g. 'mfe1')")
    component: str = Field(description="The name of the MFE component to render")
    content: dict = Field(description="The content to render in the MFE. This must be generated by a tool.")
    pin_to_pane: bool = Field(description="Set this to True if the visualization is to be placed in the right visualization pane.")
    name: str = Field(description="A unique name for the visual element.")
    description: str = Field(description="A description for the visual element.")
    id: str | None = Field(default=None, description="The ID of the visualization from the database, if it's pinned to the pane.")
    order_index: int | None = Field(default=None, description="The display order of the visualization in the right pane.")


class MFEContainer(BaseModel):
    """The final response object containing all Micro-Frontend components."""
    mfes: List[MFEContent] = Field(description="A list of MFE components to render in the UI")


class FollowUpQuestions(BaseModel):
    """Suggested follow-up questions for the user to ask the AI agent based on the conversation history."""
    follow_up_questions: List[str] = Field(description="Exactly 3 highly contextual and relevant follow-up questions the user could ask next.")


class AgentState(BaseModel):
    messages: Annotated[List[BaseMessage], add_messages] = Field(default_factory=list)
    visualizations: Annotated[List[MFEContent], operator.add] = Field(default_factory=list)
