/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#bf3003",
        "surface-tint": "#004ced",
        "inverse-on-surface": "#eef0ff",
        "tertiary-fixed": "#ffdbd2",
        "primary": "#003ec7",
        "primary-fixed": "#dde1ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#3c0800",
        "on-error": "#ffffff",
        "primary-container": "#0052ff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#d5e3fc",
        "on-tertiary-container": "#ffddd5",
        "on-surface": "#131b2e",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dae2fd",
        "on-secondary-fixed": "#0d1c2e",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eaedff",
        "surface-container-low": "#f2f3ff",
        "tertiary-fixed-dim": "#ffb4a1",
        "on-secondary-fixed-variant": "#3a485b",
        "secondary-fixed": "#d5e3fc",
        "on-secondary": "#ffffff",
        "outline-variant": "#c3c5d9",
        "on-background": "#131b2e",
        "surface-dim": "#d2d9f4",
        "on-tertiary-fixed-variant": "#891e00",
        "outline": "#737688",
        "background": "#faf8ff",
        "on-secondary-container": "#57657a",
        "primary-fixed-dim": "#b7c4ff",
        "surface-container-high": "#e2e7ff",
        "surface-bright": "#faf8ff",
        "surface-variant": "#dae2fd",
        "on-surface-variant": "#434656",
        "secondary": "#515f74",
        "on-primary-fixed": "#001452",
        "surface": "#faf8ff",
        "on-primary-fixed-variant": "#0038b6",
        "secondary-fixed-dim": "#b9c7df",
        "on-primary-container": "#dfe3ff",
        "tertiary": "#952200",
        "inverse-primary": "#b7c4ff",
        "inverse-surface": "#283044"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "manrope": ["Manrope"],
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
