---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mfe-angry-agent
spec:
  releaseName: mfe-angry-agent
  chartRef:
    kind: OCIRepository
    name: mfe-shell
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/angry-agent-ui
      tag: sha-1b97e03999b604efcd5eff24af068ac2fbdbef50
      pullPolicy: Always # Dev ONLY
    env:
      - name: SERVE_ROOT
        value: /mfe/angry-agent
    config:
      contents:
        config.json: |
          {
            "apiUrl": "/agent-be/api"
          }
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: angry-agent
spec:
  interval: 10m
  url: oci://ghcr.io/polecatworks/angry-agent/helm/agent-be
  ref:
    semver: ">= 0.1.x-0"
    semverFilter: .*-main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: angry-agent
spec:
  releaseName: angry-agent
  chartRef:
    kind: OCIRepository
    name: angry-agent
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: sha-b9dda23a75de700e3ae6acfb7d078705f6d2ef33
      pullPolicy: Always
    configs:
      webservice:
        url: http://0.0.0.0:8080/agent-be
      persistence:
        db:
          connection:
            url: postgresql://cnpg-db0-cluster-rw.dbs:5432/angry_agent
      aiclient:
        ollama_base_url: http://ollama.ollama:11434
    volumes:
      - name: configs
        configMap:
          name: '{{ template "agent-be.fullname" . }}'
      - name: secrets
        projected:
          sources:
            - secret:
                name: db0-angry-agent-user
                items:
                  - key: username
                    path: persistence/db/connection/username
                  - key: password
                    path: persistence/db/connection/password
